spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
  spring:
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    salesDataTopic: sales-data-topic